add Enzyme tests (WIP)
Test suites currently break when calling down to Quill APIs due to lack of fully-mocked browser environment

1) <ReactQuill /> calls componentDidMount:
     Error: [Parchment] Unable to create [object HTMLDivElement] blot